name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 3.0.10
homepage: https://github.com/flutterchina/dio

environment:
  sdk: '>2.4.0 <3.0.0'

dependencies:
  http_parser: ">=0.0.1 <4.0.0"
  path: ^1.7.0
  buffer: ^1.0.7
dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.2
  test_coverage: ^0.5.0
#  flutter_test:
#    sdk: flutter

